### ISSUE TITLE
Добрый день, хотел спросить, как подключить библиотеки на Windows для python, точнее, как добавить их в VS CODE 

### ISSUE THREAD

**Issue by jarosloov** [jarosloov/Algorithms_2020#3]
**
 import cv2
import pytesseract

# Путь для подключения tesseract
pytesseract.pytesseract.tesseract_cmd = 'C:\\Program Files (x86)\\Tesseract-OCR\\tesseract.exe' 
**

**Comment by justjune** [comment]
pip в командной строке cmd с именем библиотеки. Подробности тут: https://docs.python.org/3/installing/index.html В VS code ничего добавлять не нужно, просто в файле *.py должны быть import того, что вам нужно.

**Comment by jarosloov** [comment]
Спасибо!
