### ISSUE TITLE
Добрый день! 

### ISSUE THREAD

**Issue by jarosloov** [jarosloov/Algorithms_2020#4]
Я поигрался с python и написал программу, которая читает с картинки все значения и потом подсчитывает сумму всех цифры на картинке, а также произведение всех цифр(кроме нуля) .

Хотел бы узнать, можно ли получить дополнительные баллы за это?

https://github.com/jarosloov/Algorithms_2020/tree/master/Reading%20the%20receipt/%5B3%5D%20Подсчет%20всех%20цифр%20на%20картинке

**Comment by justjune** [comment]
См. Успеваемьсть ОПД
