### ISSUE TITLE
Python (домашка) 09.12.2020

### ISSUE THREAD

**Issue by jarosloov** [jarosloov/Algorithms_2020#7]
@justjune 

 **Ccылка:**   https://colab.research.google.com/drive/19TvdwfU3NqYiYYW7T-SN0fsLvYbpS5k7?usp=sharing

**Comment by justjune** [comment]
Каждый раз просить доступ на гугле не удобно!

**Comment by jarosloov** [comment]
https://repl.it/@jarosloov/test3#main.py
